"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { requireModuleAccess } from "@/lib/modules";
import { MAX_PATRIMONIO_DOCUMENT_BYTES } from "@/lib/patrimonio-fields";
import {
  patrimonioAssetSchema,
  patrimonioLiabilitySchema,
  patrimonioProtectionSchema,
  patrimonioDeleteSchema,
  patrimonioConfirmMonthlyValueSchema,
} from "@/lib/validation";

export type PatrimonioActionState = {
  error?: string;
  fieldErrors?: Record<string, string[]>;
  success?: boolean;
};

/** FormData entries come back as `null` when absent — every optional
 * field in the Gestão Patrimonial schemas (src/lib/validation.ts)
 * expects `undefined` instead, never `null`/`""`. */
function f(formData: FormData, key: string): string | undefined {
  const value = formData.get(key);
  return typeof value === "string" && value !== "" ? value : undefined;
}

async function requirePatrimonioSession() {
  const session = await getSession();
  if (!session) redirect("/login");
  // Defense in depth — src/app/(app)/patrimonio/page.tsx already guards
  // the route itself, but a direct POST to this action must be denied
  // server-side too regardless of what the page would have shown.
  await requireModuleAccess("gestao_patrimonial");
  return session;
}

type DocumentField =
  | { present: false }
  | { present: true; error: string }
  | { present: true; fileName: string; mimeType: string; fileSize: number; fileData: Uint8Array<ArrayBuffer> };

/** Reads the optional "document" file field shared by Passivos and
 * Proteção's "Documento Anexado" — absent (present: false) means the
 * caller should leave whatever's already stored untouched, never clear
 * it just because a save didn't include a new file. Plain Uint8Array
 * rather than Buffer.from(...): Buffer's `.buffer` is typed as
 * ArrayBufferLike (it can wrap a SharedArrayBuffer), which Prisma's
 * generated Bytes input type rejects — an ArrayBuffer from
 * File.arrayBuffer() never actually is one, but the wider Buffer type
 * doesn't say so. */
async function extractOptionalDocument(formData: FormData): Promise<DocumentField> {
  const file = formData.get("document");
  if (!(file instanceof File) || file.size === 0) return { present: false };
  if (file.size > MAX_PATRIMONIO_DOCUMENT_BYTES) {
    return { present: true, error: "Documento muito grande. O limite é de 5 MB." };
  }
  const fileData = new Uint8Array(await file.arrayBuffer());
  return {
    present: true,
    fileName: file.name || "documento",
    mimeType: file.type || "application/octet-stream",
    fileSize: file.size,
    fileData,
  };
}

const CLEAR_DOCUMENT_FIELDS = {
  documentFileName: null,
  documentMimeType: null,
  documentFileSize: null,
  documentData: null,
};

/** Turns an extractOptionalDocument() result (plus the edit row's
 * "Remover documento anexado" checkbox) into the Prisma `data` patch —
 * a new file always wins, otherwise the checkbox clears the existing
 * one, otherwise nothing about the document changes. Never `{}` and a
 * clear at once: a re-upload always supersedes a same-submit removal
 * request. */
function documentPatch(document: DocumentField, removeRequested: boolean) {
  if (document.present && !("error" in document)) {
    return {
      documentFileName: document.fileName,
      documentMimeType: document.mimeType,
      documentFileSize: document.fileSize,
      documentData: document.fileData,
    };
  }
  return removeRequested ? CLEAR_DOCUMENT_FIELDS : {};
}

async function hasValueHistory(kind: "asset" | "liability", id: string): Promise<boolean> {
  const where = kind === "asset" ? { assetId: id } : { liabilityId: id };
  const [changeCount, confirmationCount] = await Promise.all([
    prisma.patrimonioValueChange.count({ where }),
    prisma.patrimonioMonthlyConfirmation.count({ where }),
  ]);
  return changeCount > 0 || confirmationCount > 0;
}

export async function saveAssetAction(
  _prevState: PatrimonioActionState,
  formData: FormData
): Promise<PatrimonioActionState> {
  const session = await requirePatrimonioSession();

  const parsed = patrimonioAssetSchema.safeParse({
    id: f(formData, "id"),
    category: f(formData, "category"),
    name: f(formData, "name"),
    currentValueCents: f(formData, "currentValueCents") ?? "",
    usageType: f(formData, "usageType"),
    location: f(formData, "location"),
    liquidity: f(formData, "liquidity"),
    updateMethod: f(formData, "updateMethod") ?? "MANUAL",
    annualRatePct: f(formData, "annualRatePct"),
    rateLabel: f(formData, "rateLabel"),
    purchaseDate: f(formData, "purchaseDate"),
    purchaseValueCents: f(formData, "purchaseValueCents"),
    isRented: f(formData, "isRented"),
    rentNetValueCents: f(formData, "rentNetValueCents"),
    notes: f(formData, "notes"),
  });
  if (!parsed.success) {
    return { error: "Verifique os campos informados.", fieldErrors: parsed.error.flatten().fieldErrors };
  }
  const { id, ...data } = parsed.data;

  if (id) {
    const existing = await prisma.patrimonioAsset.findUnique({ where: { id } });
    if (!existing || existing.userId !== session.userId) {
      return { error: "Item não encontrado." };
    }
    // "Editar e atualizar" is one button covering two different things
    // (spec section 4): a pure cadastral edit never touches the value
    // history, but a changed Valor Atual also logs a
    // PatrimonioValueChange row — both writes commit together so a
    // history row is never created without the value update actually
    // landing (or vice versa).
    const valueChanged = data.currentValueCents !== existing.currentValueCents;
    await prisma.$transaction([
      prisma.patrimonioAsset.update({ where: { id }, data }),
      ...(valueChanged
        ? [
            prisma.patrimonioValueChange.create({
              data: {
                userId: session.userId,
                assetId: id,
                previousValueCents: existing.currentValueCents,
                newValueCents: data.currentValueCents,
                changedByUserId: session.realUserId,
              },
            }),
          ]
        : []),
    ]);
  } else {
    await prisma.patrimonioAsset.create({ data: { ...data, userId: session.userId } });
  }

  revalidatePath("/patrimonio");
  return { success: true };
}

/** "Excluir" — soft-deletes (isActive: false) when the item has value
 * history worth preserving (a PatrimonioValueChange row, or a monthly
 * confirmation used by the projection engine), since hard-deleting
 * would cascade-delete that history too. An item that was never
 * updated has nothing to lose, so it's removed outright instead of
 * accumulating inactive rows with zero trace value. */
export async function deleteAssetAction(formData: FormData) {
  const session = await requirePatrimonioSession();
  const parsed = patrimonioDeleteSchema.safeParse({ id: f(formData, "id") });
  if (!parsed.success) throw new Error("Item inválido.");
  const { id } = parsed.data;

  const asset = await prisma.patrimonioAsset.findUnique({ where: { id } });
  if (!asset || asset.userId !== session.userId) throw new Error("Item não encontrado.");

  if (await hasValueHistory("asset", id)) {
    await prisma.patrimonioAsset.update({ where: { id }, data: { isActive: false } });
  } else {
    await prisma.patrimonioAsset.delete({ where: { id } });
  }
  revalidatePath("/patrimonio");
}

export async function saveLiabilityAction(
  _prevState: PatrimonioActionState,
  formData: FormData
): Promise<PatrimonioActionState> {
  const session = await requirePatrimonioSession();

  const parsed = patrimonioLiabilitySchema.safeParse({
    id: f(formData, "id"),
    category: f(formData, "category"),
    name: f(formData, "name"),
    currentBalanceCents: f(formData, "currentBalanceCents") ?? "",
    installmentValueCents: f(formData, "installmentValueCents"),
    remainingInstallments: f(formData, "remainingInstallments"),
    amortization: f(formData, "amortization"),
    cetPct: f(formData, "cetPct"),
    correctionIndex: f(formData, "correctionIndex"),
    administrationFeePct: f(formData, "administrationFeePct"),
    creditValueCents: f(formData, "creditValueCents"),
    isContemplated: f(formData, "isContemplated"),
    contemplationDate: f(formData, "contemplationDate"),
    liabilityType: f(formData, "liabilityType"),
    linkedAssetId: f(formData, "linkedAssetId"),
    startDate: f(formData, "startDate"),
    expectedEndDate: f(formData, "expectedEndDate"),
    dueDate: f(formData, "dueDate"),
    notes: f(formData, "notes"),
  });
  if (!parsed.success) {
    return { error: "Verifique os campos informados.", fieldErrors: parsed.error.flatten().fieldErrors };
  }

  const document = await extractOptionalDocument(formData);
  if (document.present && "error" in document) {
    return { error: document.error, fieldErrors: { document: [document.error] } };
  }
  const documentData = documentPatch(document, f(formData, "removeDocument") === "true");

  const { id, linkedAssetId, ...rest } = parsed.data;

  if (linkedAssetId) {
    const asset = await prisma.patrimonioAsset.findUnique({ where: { id: linkedAssetId } });
    if (!asset || asset.userId !== session.userId) {
      return { error: "Bem vinculado inválido.", fieldErrors: { linkedAssetId: ["Bem vinculado inválido."] } };
    }
  }

  const data = { ...rest, linkedAssetId };

  if (id) {
    const existing = await prisma.patrimonioLiability.findUnique({ where: { id } });
    if (!existing || existing.userId !== session.userId) {
      return { error: "Item não encontrado." };
    }
    const valueChanged = data.currentBalanceCents !== existing.currentBalanceCents;
    await prisma.$transaction([
      prisma.patrimonioLiability.update({ where: { id }, data: { ...data, ...documentData } }),
      ...(valueChanged
        ? [
            prisma.patrimonioValueChange.create({
              data: {
                userId: session.userId,
                liabilityId: id,
                previousValueCents: existing.currentBalanceCents,
                newValueCents: data.currentBalanceCents,
                changedByUserId: session.realUserId,
              },
            }),
          ]
        : []),
    ]);
  } else {
    await prisma.patrimonioLiability.create({ data: { ...data, ...documentData, userId: session.userId } });
  }

  revalidatePath("/patrimonio");
  return { success: true };
}

export async function deleteLiabilityAction(formData: FormData) {
  const session = await requirePatrimonioSession();
  const parsed = patrimonioDeleteSchema.safeParse({ id: f(formData, "id") });
  if (!parsed.success) throw new Error("Item inválido.");
  const { id } = parsed.data;

  const liability = await prisma.patrimonioLiability.findUnique({ where: { id } });
  if (!liability || liability.userId !== session.userId) throw new Error("Item não encontrado.");

  if (await hasValueHistory("liability", id)) {
    await prisma.patrimonioLiability.update({ where: { id }, data: { isActive: false } });
  } else {
    await prisma.patrimonioLiability.delete({ where: { id } });
  }
  revalidatePath("/patrimonio");
}

export async function saveProtectionAction(
  _prevState: PatrimonioActionState,
  formData: FormData
): Promise<PatrimonioActionState> {
  const session = await requirePatrimonioSession();

  const parsed = patrimonioProtectionSchema.safeParse({
    id: f(formData, "id"),
    element: f(formData, "element"),
    objective: f(formData, "objective"),
    currentValueCents: f(formData, "currentValueCents"),
    idealValueCents: f(formData, "idealValueCents"),
    isNeeded: f(formData, "isNeeded"),
    isCovered: f(formData, "isCovered"),
    notes: f(formData, "notes"),
  });
  if (!parsed.success) {
    return { error: "Verifique os campos informados.", fieldErrors: parsed.error.flatten().fieldErrors };
  }

  const document = await extractOptionalDocument(formData);
  if (document.present && "error" in document) {
    return { error: document.error, fieldErrors: { document: [document.error] } };
  }
  const documentData = documentPatch(document, f(formData, "removeDocument") === "true");

  const { id, ...data } = parsed.data;

  if (id) {
    const existing = await prisma.patrimonioProtection.findUnique({ where: { id } });
    if (!existing || existing.userId !== session.userId) {
      return { error: "Item não encontrado." };
    }
    await prisma.patrimonioProtection.update({ where: { id }, data: { ...data, ...documentData } });
  } else {
    const maxOrder = await prisma.patrimonioProtection.aggregate({
      where: { userId: session.userId },
      _max: { order: true },
    });
    await prisma.patrimonioProtection.create({
      data: { ...data, ...documentData, userId: session.userId, order: (maxOrder._max.order ?? 0) + 1 },
    });
  }

  revalidatePath("/patrimonio");
  return { success: true };
}

/** Proteção never accumulates the kind of value-history this module
 * tracks for ativos/passivos (its "Valor da Proteção Atual" isn't
 * logged the same way), so unlike deleteAssetAction/deleteLiabilityAction
 * there's no history to protect — always a soft-delete, matching the
 * isActive convention every list/total here already filters on. */
export async function deleteProtectionAction(formData: FormData) {
  const session = await requirePatrimonioSession();
  const parsed = patrimonioDeleteSchema.safeParse({ id: f(formData, "id") });
  if (!parsed.success) throw new Error("Item inválido.");

  await prisma.patrimonioProtection.updateMany({
    where: { id: parsed.data.id, userId: session.userId },
    data: { isActive: false },
  });
  revalidatePath("/patrimonio");
}

/** Necessidade/Coberto's toggle switches (ProtectionTable.tsx) flip
 * straight from the table, no "Editar e atualizar" needed first — same
 * immediacy as the "Pago" toggle in Lançamentos
 * (markTransactionPaidStatusAction), so this takes a plain typed object
 * rather than FormData like every save/delete action above (there's no
 * <form> involved, the toggle calls this directly). */
export async function setProtectionFlagAction(input: {
  id: string;
  field: "isNeeded" | "isCovered";
  value: boolean;
}) {
  const session = await requirePatrimonioSession();
  const { id, field, value } = input;

  await prisma.patrimonioProtection.updateMany({
    where: { id, userId: session.userId },
    data: field === "isNeeded" ? { isNeeded: value } : { isCovered: value },
  });
  revalidatePath("/patrimonio");
}

/** "Fotografia do mês" — confirms/adjusts one bem ou dívida's value for
 * one specific month (src/lib/patrimonio.ts's sparse confirmation
 * ledger). Upsert: re-confirming the same item+month just updates the
 * value instead of erroring on the unique constraint. Deliberately
 * separate from PatrimonioValueChange (the "Editar e atualizar" history
 * above) — this is the existing monthly-projection mechanic and is left
 * untouched. */
export async function confirmMonthlyValueAction(
  _prevState: PatrimonioActionState,
  formData: FormData
): Promise<PatrimonioActionState> {
  const session = await requirePatrimonioSession();

  const parsed = patrimonioConfirmMonthlyValueSchema.safeParse({
    kind: f(formData, "kind"),
    itemId: f(formData, "itemId"),
    monthKey: f(formData, "monthKey"),
    valueCents: f(formData, "valueCents") ?? "",
  });
  if (!parsed.success) {
    return { error: "Verifique os campos informados.", fieldErrors: parsed.error.flatten().fieldErrors };
  }
  const { kind, itemId, monthKey, valueCents } = parsed.data;

  if (kind === "asset") {
    const asset = await prisma.patrimonioAsset.findUnique({ where: { id: itemId } });
    if (!asset || asset.userId !== session.userId) return { error: "Item não encontrado." };
    await prisma.patrimonioMonthlyConfirmation.upsert({
      where: { assetId_monthKey: { assetId: itemId, monthKey } },
      update: { valueCents },
      create: { userId: session.userId, assetId: itemId, monthKey, valueCents },
    });
  } else {
    const liability = await prisma.patrimonioLiability.findUnique({ where: { id: itemId } });
    if (!liability || liability.userId !== session.userId) return { error: "Item não encontrado." };
    await prisma.patrimonioMonthlyConfirmation.upsert({
      where: { liabilityId_monthKey: { liabilityId: itemId, monthKey } },
      update: { valueCents },
      create: { userId: session.userId, liabilityId: itemId, monthKey, valueCents },
    });
  }

  revalidatePath("/patrimonio");
  return { success: true };
}
